---
title: "Tutorial Part II — R goes spatial: Exercise 2"
author: "Stephanie Kramer-Schadt & Cédric Scherer"
date: "`r Sys.setlocale('LC_TIME','C'); paste('Last Update', format(Sys.time(), '%B %e, %Y')) `" 
        #"`r Sys.Date()`" # 
output:
  rmdformats::readthedown:
    highlight: kate
    code_folding: show
    toc_depth: 4
    toc_float: true
editor_options:
  chunk_output_type: inline
params:
  date: !r Sys.Date()
---

<style>
h1 {
  color: Orange ;
}
h2, h3, h4, h5, h6, legend {
  color: Indigo ;
}
p {
  line-height:170%;
}
#sidebar h2 {
  background-color: Indigo;
}
code {
  color: Indigo ;
}
.exercise {
  color: #824b00;
}
</style>

# <span class='exercise'>Course 2 Exercise 1</span>

**Please hand in the R-Script and the plots. Answer the questions after each step in the script. Please add your name or name of group to the file/script names.**

For example: myplotname_course2_ex1_yourlastname_yourfirstname.pdf/ or: .png/ or: .html and Rscript_course2_ex1_yourlastname_yourfirstname.Rmd/ or: .R

**Revisit the data set from course 1 on wild boar observations in Berlin: `data_wb_melden_en.csv`. 
(it is here: `....\d6_teaching_collection\data\data_berlin\animal_data`).

Now, we want to study the spatial patterns of the wild boar observations. We may hypothesize that wild boar observations are also related to local differences in weather. Answer the following question using spatial data sets and visualizations:**

**Question 1.1) Were wild boar with many piglets seen more often in warm parts of the city?**


Follow these steps to answer the questions:

* a. Load the wild boar data (`data_wb_melden_en.csv`) and spatial data on temperature in Berlin (`summer_temp_100m_3035.asc` in `data_berlin`). Remember to set the correct CRS to the raster! (Hint: we need the Lambert Azimuthal Equal Area (LAEA) projection for Europe. Tip: always save the CRS as EPSG code to the filename ;-) )
* b. Turn the wild boar data into a simple features object.  Remember to set the correct CRS (the wild boar locations were collected in WGS 84) and to transform it to the same CRS as the raster afterwards!
* c. Inspect both spatial data sets by plotting the temperature raster with the wild boar locations on top using the R basic plot function. The locations should match the map (if not something went wrong when setting the CRS; check if they are the same).
* d. Select one of the temperature layers and extract the values for each wild boar location. 
* e. Create a plot that visualizes the temperature at each wild boar observation with 3 or more piglets (y axis) for each number of piglets (e.g. make a boxplot and plot the raw data on top).

**Question 1.2) Were wild boars more often observed at colder spots of the city during sunny weather?**

* f. Create a new variable that holds the weather category as either "sunny" or "other".
* g. Visualize the temperature at each wild boar observation (y axis) for sunny and other weather (box and whisker plot + raw data). 
* h. Save the wild boar observations with the local temperature information as an .Rds file.

**Question 1.3) *Additional question for the fast ones:* Were large groups of wild boar more frequently seen in areas providing a dense tree cover?**

* i. Load the tree cover data set (`tree_cover_density_2012_100m_3035.asc` in `data_berlin`).
* j. Inspect the data set by plotting the raster using the R basic plot function.
* k. Extract the tree cover within a buffer of 100m around each wild boar location (hint: use the help to inspect the arguments of `extract()`). 
* l. Create a boxplot that shows the tree cover (y axis) based on the group size.

<br><hr><br>
# END

---

<details><summary>Session Info</summary>

```{r sessionInfo}
Sys.time()
sessionInfo()
```

</details>
